include: package:flutter_lints/flutter.yaml

linter:
  rules:
    require_trailing_commas: true
    no_leading_underscores_for_local_identifiers: false
    constant_identifier_names: false
    non_constant_identifier_names: false
